language: java

sudo: false
env:
  global:
    - CONSUL_VERSION=0.9.2
    - CONSUL_DC=dev1
    - CONSUL_DIR=$HOME/consul_$CONSUL_VERSION
before_script:
  - 'if [[ ! -f $CONSUL_DIR/consul ]]; then (mkdir -p $CONSUL_DIR && cd $CONSUL_DIR && wget https://releases.hashicorp.com/consul/0.9.2/consul_$(CONSUL_VERSION)_linux_amd64.zip && unzip ${CONSUL_VERSION}_linux_amd64.zip); fi'
  - $CONSUL_DIR/consul --version
  - $CONSUL_DIR/consul agent -dev &
  # Wait for consul to elect itself as leader
  - sleep 5
cache:
  directories:
    - $CONSUL_DIR
  
jdk:
  - oraclejdk8
  
install:
  - cd config-web/ && mvn clean package -DskipTests=true -Dmaven.javadoc.skip=true -B -V
