config:
  profile: dev
  token: er34xfwefwerqxrx2
  consul:
    host: localhost:8500
    ttl: 3
    port: 8080
    check: http://localhost:8080/health
    serviceId: config-web
    serviceName: config-web
  repo:
    repoDir: /home/travis/build/speedyproject/dcmp/repertory
    host: https://github.com/gksqls/config-repo
    username: 
    password: 
